# Generated by Django 4.0.3 on 2022-11-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('text', models.TextField(max_length=50, verbose_name='описание')),
                ('sm_image', models.ImageField(blank=True, null=True, upload_to='static/images/foto', verbose_name='маленькое изображение')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='static/images/foto', verbose_name='большое изображение')),
                ('show_item', models.BooleanField(default=False, verbose_name='Отобразить')),
            ],
            options={
                'verbose_name': 'проекты',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
